---
title: "Visualising COVID-19 in Peru"
author: "Varsha Ujjinni Vijay Kumar"
date: 2015-07-23T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

```{r libraries,message=FALSE,warning=FALSE,echo=FALSE}
library(tidyverse)
library(lubridate)
library(plotly)
```


```{r data-read-store, message=FALSE,warning=FALSE,echo=FALSE,eval=FALSE}
covid <- read.csv("owid-covid-data.csv")
peru <- covid %>% filter(iso_code == "PER")
peru_data <- write.csv(peru, file = "C:/Users/varsh/Documents/semester2/CWD 5523/assignment/blog-2/peru_covid.csv")
gender_table1 <- read.csv("fallecidos_covid.csv")
gender_table1 <- gender_table1 %>% rename(c(
  "ID " = "UUID",
  "Death_Date" = "FECHA_FALLECIMIENTO",
  "Age" = "EDAD_DECLARADA",
  "Sex" = "SEXO",
  "Birth_Date" = "FECHA_NAC",
  "Department" = "DEPARTAMENTO",
  "Province" = "PROVINCIA",
  "Districts" = "DISTRITO")) 
write.csv(gender_table1,file = "C:/Users/varsh/Documents/semester2/CWD 5523/assignment/blog-2/state-details.csv")
```


```{r read-data,message=FALSE,warning=FALSE,echo=FALSE}
peru_data <- read.csv("peru_covid.csv")
peru_data$date <- as_date(peru_data$date)
gender_table <- read.csv("state-details.csv")
```


[More Information on COVID-19](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/question-and-answers-hub/q-a-detail/q-a-coronaviruses)


```{r plot-cases,message=FALSE,warning=FALSE}
peru_data <- peru_data %>% mutate(month = month(date))
p1 <- ggplot(peru_data,aes(x = date),size = 1.0) + 
  geom_line(aes(y = total_cases, color = "total_cases"),size = 1.0)+
  geom_line(aes(y = total_deaths,color = "total_deaths"),size = 1.0)+
  theme_minimal() +
  ylab("Total Cases") +
  xlab("Month")+
  theme(legend.title = element_blank(),axis.text.y = element_blank())+
  #scale_x_continuous(breaks = scales::pretty_breaks()) +
  labs(title="Count of Covid19 cases(total cases and Deaths)")
ggplotly(p1)
```

```{r new-cases,warning=FALSE,message=FALSE}
p2 <- ggplot(peru_data,aes(x = date, y = new_cases)) +
  geom_point(color = "#69b3a2") + 
  geom_smooth() +
  theme_minimal() +
  theme(axis.text.y = element_blank())+
  ylab("New cases") +
  xlab("Month")
ggplotly(p2)
```



```{r high-province,message=FALSE,warning=FALSE}
gender_table <- read.csv("state-details.csv")
provinces <- gender_table %>% group_by(Province) %>% count(Province,sort = TRUE) %>% head()
ggplot(provinces,aes(x = Province, y = n,fill = Province)) + 
  geom_col() + 
  coord_flip() +
  ylab("Deaths") +
  theme_minimal() +
  theme(legend.position= "none") 
```

```{r gender-plot,message=FALSE,warning=FALSE}
gender <- gender_table %>% group_by(Sex,Province) %>% count(Sex,sort = TRUE) %>% head(25)
ggplot(gender,aes(x = n, y = Province,fill = Sex)) + 
  geom_col() + 
  facet_wrap(~Sex)  + 
  xlab("Deaths") +
  theme_minimal() +
  theme(legend.position = "none") 
```

```{r age-plot,message=FALSE,warning=FALSE}
Age <- gender_table %>% group_by(Sex,Age) %>% count(Age,sort = TRUE) 
ggplot(Age,aes(x = Age, y = n,fill = Sex)) + 
  geom_col(binwidth = 10) + 
  facet_wrap(~Sex)  + 
  ylab("Deaths") +
  theme_minimal() +
  theme(legend.position = "none") +
  xlim(0,50)
```
